typography_spectrum: 0.1978896
color:
  saturation: 0.907143
  brandStrength: 0.7254218
  rhythmicContrast: 0.07199423
  brandColors:
    - '#000000'
    - '#FCFCFC'
    - '#A4A4A4'
    - '#393939'
    - '#666666'
  lightness: 0.49968
layout_spectrum: 0
name: Pulsar Energy Drink
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Pulsar Energy Drink
